### PR TITLE
Fix security issues

### PR DESCRIPTION
**Pull request by bethleha**
Thanks to GitHub for notifying this https://github.com/indix/indix.github.io/network/alerts

@manojlds or @ashwanthkumar Please review and merge this.

/cc @arijit-indix

### CODE REVIEW

**Comment by arijit-indix** [comment]
👍

**Review by ashwanthkumar — APPROVED** [review]
Please do check if the build goes through fine on travis post merging this change.

**Review by ashwanthkumar — CHANGES_REQUESTED** [review]
I just checked the build failure. Changing the `.lock` directly file is not the right thing to do. Please update the Gemfile and do a `bundle install` to regenerate the `.lock` file again.

**Comment by bethleha** [comment]
> I just checked the build failure. Changing the `.lock` directly file is not the right thing to do. Please update the Gemfile and do a `bundle install` to regenerate the `.lock` file again.

@ashwanthkumar Can we just remove the lock file from the source-tree? As This file is generated during the build-phase of the project.

**Review by ashwanthkumar-avalara — APPROVED** [review]

**Pull request merged**
